<a href="https://colab.research.google.com/github/seokjinwoo/AIandEcon/blob/main/lec1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 파이썬 기초

- 기초 프로그래밍
- 마크다운 문법 markdown
- 필기 필요할 때는 text, 코딩이 필요할 때는 파이썬 코딩
- 모형이 필요할 때는 LaTex 을 이용해서 표현
- 예를 들어서, 다음과 같은 회귀모형을 쓸 수 있음

$$
y_i = a + b x_i + \varepsilon_i
$$

---

- 문자 프린팅

In [2]:
print("Hello, World!")
print('Hello, World!')

Hello, World!
Hello, World!


In [3]:
print("Hello", "World!")

Hello World!


In [4]:
print("Fit a model with", 10, "variables")

Fit a model with 10 variables


In [7]:
# +: 연결 concantenation
print("Hello" + " " + "World!")

Hello World!


In [11]:
print?

### 파이썬에서의 연산

In [14]:
3 + 5 # 더하기

8

In [17]:
3 * 5 # 곱하기

15

In [18]:
2**3  # 제곱(power)

8

In [19]:
1/3 # 나누기

0.3333333333333333

- 데이터를 다뤄야 하기 때문에 숫자를 담는 그릇에 대해서.
- 리스트(list), 튜플(tuple), 배열(array), 데이터프레임(dataframe) 등

In [25]:
# 리스트, bracket
x = [1,2,3,4,5 ]
# print("x는", x)
y = [10, 9, 8]

x + y

[1, 2, 3, 4, 5, 10, 9, 8]

---
- 파이썬 패키지. 라이브러리.
- 수학과 관련된 패키지 중에서 가장 많이 사용되는 것이 numpy
- 넘파이에 있는 array() 를 이용해서 숫자들을 저장

In [27]:
# numpy의 약자가 np
import numpy as np


In [35]:
x = np.array([3, 4, 5])
# print(x)

# 4, 9, 7 을 y의 array 형태로 담아보자
y = np.array([4, 9, 7])

print(x + y)
print(x * y)

[ 7 13 12]
[12 36 35]


In [39]:
# dim = 1 -> dim = 2 차원을 확장할 수 있음(제한)

z = np.array([ [1,2,5], [3,4,8] ])
print(z)
print("z는", z.ndim, "차원입니다.")

[[1 2 5]
 [3 4 8]]
z는 2 차원입니다.


In [43]:
print(z.dtype) # 데이터의 타입
print(z.shape) # 차원이 어떻게 구성되어 있냐

int64
(2, 3)


In [45]:
np.sum(z)

23